#ifndef _ARXPORT_AD_ACADI_H_
#define _ARXPORT_AD_ACADI_H_ 1


#include "..\inc\IcadTLB.h"

#define IAcadPoint							IIcadPoint
#define IAcadPoints							IIcadPoints
#define IAcadVector							IIcadVector
#define IAcadMatrix							IIcadMatrix
#define IAcadLibrary						IIcadLibrary
#define IAcadUtility						IIcadUtility
#define IAcadHyperlinks						IIcadHyperlinks
#define IAcadHyperlink						IIcadHyperlink
#define IAcadAcCmColor						IIcadAcCmColor
#define IAcadPlotterPen						IIcadPlotterPen
#define IAcadPlotterPens					IIcadPlotterPens
#define IAcadPlotProperties					IIcadPlotProperties
#define IAcadPlotManager					IIcadPlotManager
#define IAcadPlotRegManager					IIcadPlotRegManager
#define IAcadMenuBar						IIcadMenuBar
#define IAcadMenuGroups						IIcadMenuGroups
#define IAcadMenuGroup						IIcadMenuGroup
#define IAcadPopupMenus						IIcadPopupMenus
#define IAcadPopupMenu						IIcadPopupMenu
#define IAcadPopupMenuItem					IIcadPopupMenuItem
#define IAcadToolbars						IIcadToolbars
#define IAcadToolbar						IIcadToolbar
#define IAcadToolbarItem					IIcadToolbarItem
#define IAcadDocuments						IIcadDocuments
#define IAcadWindows						IIcadWindows
#define IAcadWindow							IIcadWindow
#define IAcadApplication					IIcadApplication
#define _DAcadApplicationEvents				IZwcadApplicationEvents //?
#define IAcadWorkspace						IIcadWorkspace
#define IAcadWorkspaceEvents				_IcadWorkspaceEvents //?
#define IAcadApplicationPreferences			IIcadApplicationPreferences
#define IAcadGroups							IIcadGroups
#define IAcadDbItem							IIcadDbItem
#define IAcadGroup							IIcadGroup
#define IAcadState							IIcadState
#define IAcadXRecord						IIcadXRecord
#define IAcadDictionary						IIcadDictionary
#define IAcadDictionaries					IIcadDictionaries
#define IAcadPlotConfiguration				IIcadPlotConfiguration
#define IAcadPlotConfigurations				IIcadPlotConfigurations
#define IAcadLayout							IIcadLayout
#define IAcadLayouts						IIcadLayouts
#define IAcadPlot							IIcadPlot
#define IAcadTableItem						IIcadTableItem
#define IAcadRegisteredApplication			IIcadRegisteredApplication
#define IAcadRegisteredApplications			IIcadRegisteredApplications
#define IAcadEntities						IIcadEntities
#define IAcadBlock							IIcadBlock
#define IAcadBlocks							IIcadBlocks
#define IAcadDimensionStyle					IIcadDimensionStyle
#define IAcadDimensionStyles				IIcadDimensionStyles
#define IAcadLayer							IIcadLayer
#define IAcadLayers							IIcadLayers
#define IAcadLinetype						IIcadLinetype
#define IAcadLinetypes						IIcadLinetypes
#define IAcadTextStyle						IIcadTextStyle
#define IAcadTextStyles						IIcadTextStyles
#define IAcadUserCoordSystem				IIcadUserCoordSystem
#define IAcadUserCoordSystems				IIcadUserCoordSystems
#define IAcadView							IIcadView
#define IAcadViews							IIcadViews
#define IAcadViewport						IIcadViewport
#define IAcadViewports						IIcadViewports
#define IAcadSelectionSet					IIcadSelectionSet
#define IAcadSelectionSets					IIcadSelectionSets
#define IAcadSummaryInfo					IIcadSummaryInfo
#define IAcadSortentsTable					IIcadSortentsTable
#define IAcadEntity							IIcadEntity
#define IAcad3DFace							IIcad3DFace
#define IAcad3DPoly							IIcad3DPoly
#define IAcadArc							IIcadArc
#define IAcadAttribute						IIcadAttribute
#define IAcadAttributeReference				IIcadAttributeReference
#define IAcadAttributeReferences			IIcadAttributeReferences
#define IAcadBlockReference					IIcadBlockReference
#define IAcadCircle							IIcadCircle
#define IAcadEllipse						IIcadEllipse
#define IAcadHatch							IIcadHatch
#define IAcadLeader							IIcadLeader
#define IAcadLine							IIcadLine
#define IAcadLightWeightPolyline			IIcadLightWeightPolyline
#define IAcadMText							IIcadMText
#define IAcadPointEntity					IIcadPointEntity
#define IAcadPolyline						IIcadPolyline
#define IAcadPolygonMesh					IIcadPolygonMesh
#define IAcadPolyfaceMesh					IIcadPolyfaceMesh
#define IAcadPViewport						IIcadPViewport
#define IAcadRasterImage					IIcadRasterImage
#define IAcadRay							IIcadRay
#define IAcadShape							IIcadShape
#define IAcadSolid							IIcadSolid
#define IAcadSpline							IIcadSpline
#define IAcadText							IIcadText
#define IAcadTolerance						IIcadTolerance
#define IAcadTrace							IIcadTrace
#define IAcadXline							IIcadXline
#define IAcadExternalReference				IIcadExternalReference
#define IAcadRegion							IIcadRegion
#define IAcadMLine							IIcadMLine
#define IAcadOle							IIcadOle
#define IAcad3DSolid						IIcad3DSolid
#define IAcadDimension						IIcadDimension
#define IAcadDimAngular						IIcadDimAngular
#define IAcadDimAligned						IIcadDimAligned
#define IAcadDimDiametric					IIcadDimDiametric
#define IAcadDimOrdinate					IIcadDimOrdinate
#define IAcadDimRadial						IIcadDimRadial
#define IAcadDimRotated						IIcadDimRotated
#define IAcadDim3PointAngular				IIcadDim3PointAngular
#define IAcadModelSpace						IIcadModelSpace
#define IAcadPaperSpace						IIcadPaperSpace
#define IAcadDocument						IIcadDocument
#define _DAcadDocumentEvents				_EIcadDocument 
#define IAcadDatabasePreferences			IIcadDatabasePreferences

#define  AcPlotPaperUnits					ZcPlotPaperUnits
#define  AcPlotRotation						ZcPlotRotation
#define  AcPlotType							ZcPlotType
#define  AcRegenType						ZcWhichViewport/*ZcRegenType*/

#endif